- configurations/values.py
- tests/test_values.py
When assigning False to a BooleanValue and reusing it was raising a
ValueError exception because BooleanValue was evaluating False as None.
Thanks to @abbottc for catching this error.
> Fixed wrong behaviour when assigning BooleanValue

- configurations/values.py
- tests/test_values.py
I thought it would be nice to be able to pass additional arguments to casters.
Specific example would be an ability to set custom database engine in dj-database-url:
https://github.com/kennethreitz/dj-database-url/pull/26
> Ability to pass keyword args to CastingMixin casters

- tox.ini
This commit extends `Remove coverage env from travis config` f1f997354798acb5eb330280b656530d62aec0dd
> Remove coverage env from `tox.ini`

- configurations/importer.py
- configurations/utils.py
- tests/test_cli.py
- tox.ini
@jezdez I added a django version check to use `CommandParser` instead of `LaxOptionParser` if django>=1.8. I've tested it locally, this commit closes #65. django-configurations and pytest-django tests succeed.
> Use CommandParser instead of LaxOptionParser in django1.8 

- setup.py
this helps when deploying configurations where the app is deployed as bdist_wheel
> add entrypoints to run in non-source-tree installs

- configurations/importer.py
- tests/management/commands/old_optparse_command.py
- tests/requirements.txt
- tests/test_main.py
**Disclaimer**: I have read the discussions in https://github.com/jezdez/django-configurations/issues/105#issuecomment-88895512 and https://github.com/jezdez/django-configurations/commit/0ff4c7612d28036449edd4b2cf3b58ca1eded0f2, and I understand the situation this package is in. I pondered long and hard as to whether I should even open this pr.
I completely get it; by the time I am done: root-causing this issue, learning how configurations works, learning what the Django guys were trying to do in 1.8, learning how to run tox, writing tests, and finally authoring this pr, I will have spent _many hours_ on these three lines of diff. Hours I could have spent on "real work". I'm just fortunate -- and love (and need) this package enough! -- that my current workload happens to be light enough, …
> Fix optparse fallback logic in Django 1.8+

- docs/patterns.rst
Django 1.9 makes the languages setting a list of tuples.
> Handle example usage for Django 1.9

- configurations/utils.py
- tests/test_values.py
It's better to try the new import method first because in Django<1.9 the
old method is still available and will raise a RemovedInDjango19Warning
that we could have avoided.
> Fixed RemovedInDjango19Warning

- tests/test_values.py
`dj-email-url` added support for `EMAIL_USE_SSL` in its latest version.
> Add `EMAIL_USE_SSL` to tests

- README.rst
- configurations/base.py
- docs/cookbook.rst
- setup.py
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- configurations/values.py
- tests/test_values.py
I noticed that truthy and falsey of Value class wasn't the expected. An example extracted directly from python console:
```
In [1]: from configurations.values import BooleanValue
In [2]: test = BooleanValue(False)
In [3]: test
Out[3]: False
In [4]: bool(test)
Out[4]: True
```
That is because `__bool__` method (`__nonzero__` for python 2) isn't implemented so is acting with default behavior, that is a `bool(self)`. In this case, the truthy or falsey value depends on value property of this class.
This is the behavior after change:
```
In [1]: from configurations.values import BooleanValue
In [2]: test = BooleanValue(False)
In [3]: test
Out[3]: False
In [4]: bool(test)
Out[4]: False
```
> Fix truthy and falsey of values

- .gitignore
- .travis.yml
- configurations/__init__.py
- setup.py
- tests/settings/main.py
- tests/settings/mixin_inheritance.py
- tests/settings/multiple_inheritance.py
- tests/settings/single_inheritance.py
- tests/test_inheritance.py
- tests/test_main.py
- tests/test_sphinx.py
- tests/test_values.py
- tests/urls.py
- tox.ini
- Drop django==1.9 as it reached end of life
- Drop python2.6, python3.3 and bring python3.6
- Bring django-2.0 in the matrix as expected failure until we add its
support
> Drop unmaintained version of  django and python

- .coveragerc
This will generate a better coverage.xml file, which makes it easier for
codecov hopefully.
Old:
<sources>
<source>…/Vcs/django-configurations/configurations</source>
<source>…/Vcs/django-configurations/tests</source>
</sources>
<packages>
<package branch-rate="0.7178" complexity="0" line-rate="0.8902" name=".">
New:
<sources>
<source>…/Vcs/django-configurations</source>
</sources>
<packages>
<package branch-rate="0.712" complexity="0" line-rate="0.8126" name="configurations">
Fixes https://github.com/jazzband/django-configurations/commit/d364802a8aa8562371769f5445efb72a83786576#commitcomment-24826518.
> .coveragerc: use include instead of multiple sources

- docs/patterns.rst
Hopefully this saves time for new users of django-configuration (like myself), who "just needed" to lazily evaluate a string inside a dictionary.
This doubles as an example for `RAVEN_CONFIG` which was the whole reason I was here in the first place... The actual problem I faced was that a setting remains of type `values.Value` when nested inside a dictionary. Which results in a weird issues like this:
```
Traceback (most recent call last):
self.client.http_context(self.get_http_context(environ))
File "/app/.heroku/python/lib/python3.6/site-packages/raven/middleware.py", line 98, in __call__
File "/app/.heroku/python/lib/python3.6/site-packages/raven/contrib/django/models.py", line 54, in <lambda>
__getattr__ = lambda x, o: getattr(get_client(), o)
File …
```
> Docs: explicitly describe property in patterns.rst

- configurations/values.py
- docs/values.rst
- tests/test_values.py
I have recently identified a requirement when working with django-configurations where I needed only a positive integer value.  I thought others may benefit from this feature too.
> extended IntegerValue to only allow positive integers

- .travis.yml
- docs/changes.rst
- tests/test_main.py
Per https://www.djangoproject.com/download/, Django 1.8 support ended in April 2018 and Django 1.10 support ended in December 2017.  
Django master also now explicitly [requires](https://github.com/django/django/commit/32ade4d73b50aed77efdb9dd7371c17f89061afc) Django 3.5+, so drop testing against Django master on Python 3.4.
Let's drop those test cases from Travis.
NOTE: I would add support for Python 3.7 in Travis as well, but that's not available upstream yet. ref: https://github.com/travis-ci/travis-ci/issues/9815
> Drop obsolete Django 1.8 and 1.10 from Travis configs

- .gitignore
- configurations/__init__.py
- sitecustomize.py
- tests/setup_test.py
- tests/test_main.py
- tox.ini
Without this, using `configurations.setup()` after Django has been setup
already re-triggers the logging configuration, which then causes e.g.
pytest's caplog to not work anymore.
TODO:
~~- [ ] revisit (revert?) #197~~
> _setup: do not call django.setup() if settings are configured already

- configurations/utils.py
- tests/test_main.py
This is the case for e.g. `bdb.BdbQuit`.
> Fix utils.reraise for exceptions without args

- README.rst
These changes add a few additional badges to the README. Thus should enhance transparency and make the project on PyPI more easily acessible.
Note that this now shows that [building the docs failed](https://readthedocs.org/projects/django-configurations/builds/8246517/). Not sure why, because building them locally doesn't fail asking for a `tests/requirements.txt` file. :confused:
> More badges to display project properties (README)

- configurations/utils.py
Looks like we're fine without `django.utils.importlib`, which is removed in Django 1.9 and deprecated since at least Django 1.7.
Relates to issue #190.
> Remove deprecated import (gone in Django 1.9)

- docs/cookbook.rst
Adds an explaination on how to read `.env` files to the documentation.
Fixes #165.
> Explain how to read .env files

- docs/cookbook.rst
- docs/patterns.rst
These changes fix a bug in a code sample for `DOTENV` and try to mitigate the concerns expressed in https://github.com/jazzband/django-configurations/pull/213#issuecomment-445557128 by @blueyed.
I've also attempted to replace the [Property settings example](https://django-configurations.readthedocs.io/en/latest/patterns/?highlight=sentry#property-settings) featuring (an outdated use of) Sentry by something more neutral, to avoid confusion.
Code markup now uses `code-block`, consistently, and I've trimmed line length to max. 72 where it made sense.
> Move Sentry recommendations to Cookbook section

- .travis.yml
- configurations/base.py
- configurations/utils.py
- configurations/values.py
- docs/changes.rst
- setup.py
- tests/settings/main.py
- tests/urls.py
- tox.ini
Replaces `django.utils.six` with `six` to support newer Django versions.
Updates Tox config to:
- remove unsupported Django versions
- add pypy3
- add Django 2.2
- update djmaster Python versions with those supported by Django 3.0
Comments admin app & URLs in test directory to avoid errors raised by missing settings required by the Django admin.
Closes #241
> Update tested Python & Django versions

- configurations/version.py
I noticed when running `manage.py runserver` in my own project, the version string was missing from the announcement. I was seeing the message `django-configurations version , using configuration LocalDev` in my logs. I checked the result of `get_distribution("configurations.version")` within a python shell, and discovered it was raising the following exception string `pkg_resources.DistributionNotFound: The 'configurations.version' distribution was not found and is required by the application`.
This patch should fix the `__version__` variable. I noticed in the commit that introduced this change, the `docs/conf.py` file had the correct use of the `get_distribution` call so I just used it in the `version.py` file as well: https://github.com/jazzband/django-configurations/commit/42641f5eb458 …
> fix version string at runtime

- docs/changes.rst
> Prepare next release 2.4

- .github/workflows/release.yml
From https://github.com/pypa/gh-action-pypi-publish/blob/unstable/v1/README.md:
The `master` branch version has been sunset. Please, change the
GitHub Action version you use from `master` to `release/v1` or use
an exact tag, or a full Git commit SHA.
From https://github.com/jazzband/django-configurations/actions/runs/2964967412:
> build: # >> PyPA publish to PyPI GHA: UNSUPPORTED GITHUB ACTION VERSION <<#L1
> You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use …
> Pin publish action in release workflow

- configurations/base.py
- configurations/values.py
- docs/patterns.rst
There are small typos in:
- configurations/base.py
- configurations/values.py
- docs/patterns.rst
Fixes:
- Should read `whether` rather than `wether`.
- Should read `overridden` rather than `overriden`.
- Should read `environment` rather than `enviroment`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- .github/workflows/test.yml
- docs/changes.rst
- setup.py
- tox.ini
> Fixed #344 - Run tests on python 3.11

- configurations/base.py
- docs/changes.rst
- tox.ini
This fixes
```
django.core.exceptions.ImproperlyConfigured: STATICFILES_STORAGE/STORAGES are mutually exclusive.
```
when running on Django 4.2 or later. See https://docs.djangoproject.com/en/dev/releases/4.2/#custom-file-storages
This currently blocks pytest-django support for 4.2 (pytest-django has django-configurations support), so a release including this change will be appreciated!
> Fix "STATICFILES_STORAGE/STORAGES are mutually exclusive" on Django>=4.2

- configurations/importer.py
This project uses the `imp` module which has been deprecated since Python 3.4 and set for removal in 3.12: 
- Raised `PendingDeprecationWarning` since 3.4 (2014)
- Raised `DeprecationWarning` since 3.5 (2015)
- Updated `DeprecationWarning` to say removal in 3.12 since 3.10 (2021)
- Removal planned for 3.12 (2023)
This change removes the dependency on `imp` in favour of `importlib`.
Co-authored-by: @jbkkd
Inspired by: @mgorny
https://github.com/jazzband/django-configurations/issues/358
> Replace imp with importlib

- .github/workflows/test.yml
- tests/test_values.py
Fix failing tet due to change in v2.2.0 (2024-05-28) of dj-database-url which added an extra param DISABLE_SERVER_SIDE_CURSORS
Fix the codecoverage action
> Fix code coverage and newly failing test

- configurations/base.py
- docs/changes.rst
Prevent this warning:
```
$ python -Wall manage.py help
/.../django/conf/__init__.py:214: RemovedInDjango60Warning: The FORMS_URLFIELD_ASSUME_HTTPS transitional setting is deprecated.
warnings.warn(
...
```
The approach of listing the setting in `deprecated_settings` is the same as for `STORAGES` in #349, but it does not need to be conditional.
> Prevent FORMS_URLFIELD_ASSUME_HTTPS warning on Django 5.0
